### ISSUE TITLE
Cannot load symbol cudnnCreateTensorDescriptor

### ISSUE THREAD

**Issue by JoeyOwens39** [QuentinFuxa/whisper_streaming_web#271]
Im using CachyOS linux with GNOME 49, not sure if i missed a step or did something wrong, using a python virtual environment 

transcribe ❯ whisperlivekit-server --host 0.0.0.0 --port 80 --model small.en
INFO:     Started server process [114576]
INFO:     Waiting for application startup.
Simulstreaming will use Faster Whisper for the encoder.
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
fish: Job 1, 'whisperlivekit-server --host 0.…' terminated by signal SIGABRT (Abort)

<img width="1696" height="542" alt="Image" src="https://github.com/user-attachments/assets/66e3b3d3-0e23-4eea-82c9-a8cda5359500" />

**Comment by QuentinFuxa** [comment]
Hi, this error means your system can’t find a compatible cuDNN library. Faster-Whisper requires that your CUDA + cuDNN versions match the PyTorch/CTranslate2 builds you've installed.

On Arch/CachyOS the easiest fix is usually:

```bash
sudo pacman -S cuda cudnn
sudo ldconfig
```

Then ensure the cuDNN `.so` files are visible:

```bash
ls /usr/lib/libcudnn*
```

If you installed PyTorch via `pip`, verify the CUDA version it expects:

```bash
python - <<EOF
import torch
print(torch.version.cuda)
EOF
```

Match that with your installed CUDA:

```bash
nvcc --version
```

**Comment by JoeyOwens39** [comment]
> Hi, this error means your system can’t find a compatible cuDNN library. Faster-Whisper requires that your CUDA + cuDNN versions match the PyTorch/CTranslate2 builds you've installed.
> 
> On Arch/CachyOS the easiest fix is usually:
> 
> sudo pacman -S cuda cudnn
> sudo ldconfig
> Then ensure the cuDNN `.so` files are visible:
> 
> ls /usr/lib/libcudnn*
> If you installed PyTorch via `pip`, verify the CUDA version it expects:
> 
> python - <<EOF
> import torch
> print(torch.version.cuda)
> EOF
> Match that with your installed CUDA:
> 
> nvcc --version

thank you it works now, i do have a strange error with it though, sometimes the text it shows will bounce up and down on the screen really fast. Also i tried --diarization but got errors with that




`transcribe ❯ pip install nemo_toolkit['asr']

Building wheel for ml_dtypes (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ml_dtypes (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-313
      creating build/lib.linux-x86_64-cpython-313/ml_dtypes
      copying ml_dtypes/_iinfo.py -> build/lib.linux-x86_64-cpython-313/ml_dtypes
      copying ml_dtypes/_finfo.py -> build/lib.linux-x86_64-cpython-313/ml_dtypes
      copying ml_dtypes/__init__.py -> build/lib.linux-x86_64-cpython-313/ml_dtypes
      copying ml_dtypes/py.typed -> build/lib.linux-x86_64-cpython-313/ml_dtypes
      running build_ext
      building 'ml_dtypes._ml_dtypes_ext' extension
      creating build/temp.linux-x86_64-cpython-313
      creating build/temp.linux-x86_64-cpython-313/ml_dtypes
      creating build/temp.linux-x86_64-cpython-313/ml_dtypes/_src
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -march=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mpclmul -fno-semantic-interposition -g -ffile-prefix-map=/tmp/pkg/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -fno-semantic-interposition -march=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mpclmul -fno-semantic-interposition -g -ffile-prefix-map=/tmp/pkg/src=/usr/src/debug/python -flto=auto -march=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mpclmul -fno-semantic-interposition -g -ffile-prefix-map=/tmp/pkg/src=/usr/src/debug/python -flto=auto -fPIC -Ithird_party/eigen -Iml_dtypes -I/tmp/pip-build-env-t9ljh83i/overlay/lib/python3.13/site-packages/numpy/_core/include -I/home/josepho/transcribe/include -I/usr/include/python3.13 -c ml_dtypes/_src/dtypes.cc -o build/temp.linux-x86_64-cpython-313/ml_dtypes/_src/dtypes.o -std=c++17 -DEIGEN_MPL2_ONLY -fvisibility=hidden -ftrapping-math
      In file included from third_party/eigen/Eigen/Core:205,
                       from ml_dtypes/_src/dtypes.cc:32:
      third_party/eigen/Eigen/src/Core/arch/AVX512/TrsmKernel.h:51:10: fatal error: TrsmUnrolls.inc: No such file or directory
         51 | #include "TrsmUnrolls.inc"
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ml_dtypes
  Building wheel for editdistance (pyproject.toml) ... done
  Created wheel for editdistance: filename=editdistance-0.8.1-cp313-cp313-manylinux_2_42_x86_64.whl size=395974 sha256=de0635a6262839e0a6f2f4e29208c0fce554cfcf321aaec92040704d1d684d4e
  Stored in directory: /home/josepho/.cache/pip/wheels/5d/f0/83/35579f35f97d5b90384045f587f969100fd0ee02b80fe95317
  Building wheel for kaldi-python-io (pyproject.toml) ... done
  Created wheel for kaldi-python-io: filename=kaldi_python_io-1.2.2-py3-none-any.whl size=9008 sha256=710096ada26721f2fafeb7b49083fb3547c05592745e7f023d1772c632e1bf72
  Stored in directory: /home/josepho/.cache/pip/wheels/5c/93/62/04ab2b6586d42b43a54b97107fca2a3448f645e2e6c4c5e6eb
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13812 sha256=616d6d73508ce58a2ffd4c7302f1ebf882c58ed177e24da86315bb3187c6706c
  Stored in directory: /home/josepho/.cache/pip/wheels/0b/1d/03/175286677fb5a1341cc3e4755bf8ec0ed08f3329afd67446b0
  Building wheel for wget (pyproject.toml) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9667 sha256=a44515064b8a63375665f8ea415a63bc6f3f7a60868aed3ec8acb76abe950911
  Stored in directory: /home/josepho/.cache/pip/wheels/8a/b8/04/0c88fb22489b0c049bee4e977c5689c7fe597d6c4b0e7d0b6a
Successfully built nemo_toolkit ctc_segmentation antlr4-python3-runtime numpy sox intervaltree editdistance kaldi-python-io docopt wget
Failed to build ml_dtypes
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> ml_dtypes`

**Comment by QuentinFuxa** [comment]
env/cudnn issue - answered in thread with fix instructions. closing
