### ISSUE TITLE
Won't use GPU on DGX Spark

### ISSUE THREAD

**Issue by paoloprandini** [QuentinFuxa/whisper_streaming_web#284]
It seems that the torch installed is not compiled with CUDA enabled, I noticed it always used the CPU only and
setup a small script with torch.zeros(1).cuda() :

 File "/home/paolo/testcuda.py", line 4, in <module>
    torch.zeros(1).cuda()
  File "/home/paolo/wlk/lib/python3.12/site-packages/torch/cuda/__init__.py", line 403, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How can install a Torch with CUDA enabled?
Thanks a lot
Paolo

**Comment by AeneasChristodoulou** [comment]
I had a similar issue. 
I found out that you can get Torch with CUDA using pip:
```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cuxxx
```
Replace the xxx with the Cuda you need, i.e. cu126 for 12.6 or 128 for 12.8.
You can also check whether it uses you GPU and cude with something like this:

```python
import torch
print("Is Cuda available? ", torch.cuda.is_available())
print("How many devices are available? ", torch.cuda.device_count())
print("What device is used? ", torch.cuda.current_device())
print("What is the name of the device? ",torch.cuda.get_device_name(torch.cuda.current_device()))
```

For me this returns:
```
Is Cuda available?  True
How many devices are available?  1
What device is used?  0
What is the name of the device?  NVIDIA RTX 4000 Ada Generation Laptop GPU
```

**Comment by paoloprandini** [comment]
I had already found out that I need to do
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu130
After this I get the same response as yours but of course with device name NVIDIA GB10
Unfortunately if I try to run
wlk --model medium --language it
I get
INFO:     Started server process [21906]
INFO:     Waiting for application startup.
Simulstreaming will use Faster Whisper for the encoder.
ERROR:whisperlivekit.simul_whisper.simul_whisper:Model warmup failed: Could not infer dtype of ctranslate2._ext.StorageView
Traceback (most recent call last):
   File "/home/paolo/wlk/lib/python3.12/site-packages/whisperlivekit/simul_whisper/simul_whisper.py", line 194, in warmup
     self.infer(is_last=True)
   File "/home/paolo/wlk/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "/home/paolo/wlk/lib/python3.12/site-packages/whisperlivekit/simul_whisper/simul_whisper.py", line 445, in infer
     encoder_feature = torch.as_tensor(encoder_feature_ctranslate, device=self.device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Could not infer dtype of ctranslate2._ext.StorageView
INFO:     Application startup complete.

I am not skilled enough to solve this type of error...

Il 25/11/2025 14:22, Aeneas Antonio Christodoulou ha scritto:

**Comment by AeneasChristodoulou** [comment]
Do you have the latest Version of all the dependencies and WLK? 

What version of pytorch do you have? What NVIDIA Cuda/Drivers to you have installed? Have you checked what version of ctranslate you have? I think I read somewhere, that there also is a ctranslate2 that comes packaged with cuda.

I am using Cuda 12.6 without that issue (on a (sadly Windows) Workstation Laptop). 

Also, what does this show you:
```python
import torch
print("Is Cuda available? ", torch.cuda.is_available())
print("How many devices are available? ", torch.cuda.device_count())
print("What device is used? ", torch.cuda.current_device())
print("What is the name of the device? ",torch.cuda.get_device_name(torch.cuda.current_device()))

import ctranslate2
print("CTranslate2 device count: ", ctranslate2.get_cuda_device_count())
print("CTranslate2 compute type CPU 1: ", ctranslate2.get_supported_compute_types("cpu", 1))
print("CTranslate2 compute type CUDA 1: ", ctranslate2.get_supported_compute_types("cuda", 1))
```

**Comment by paoloprandini** [comment]
Is Cuda available?  True
How many devices are available?  1
What device is used?  0
What is the name of the device?  NVIDIA GB10
CTranslate2 device count:  0
CTranslate2 compute type CPU 1:  {'int8_float32', 'int8', 'float32'}
Traceback (most recent call last):
  File "/home/paolo/wlk/a.py", line 10, in <module>
    print("CTranslate2 compute type CUDA 1: ", ctranslate2.get_supported_compute_types("cuda", 1))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: This CTranslate2 package was not compiled with CUDA support

**Comment by AeneasChristodoulou** [comment]
Okay, so in this case you need to get a wheel of CTranslate2 that has Cuda with it, as I suspected. So you need to find a wheel compiled with your Cuda (so 13.0=130)

**Comment by paoloprandini** [comment]
The problem is that no CTranslate2 wheel is available for Cuda 13.0 and aarch64
I tried compiling CTranslate2 by myself ( not an easy job ) and then when I run again I get another error

triton.runtime.errors.PTXASError: PTXAS error: Internal Triton PTX codegen error
`ptxas` stderr:
ptxas fatal   : Value 'sm_121a' is not defined for option 'gpu-name'

**Comment by paoloprandini** [comment]
I noticed the suggestion
pip install ctranslate2==4.5.0 -f https://opennmt.net/ctranslate2/whl/cu130
but it is not compiled for CUDA on aarch64

**Comment by paoloprandini** [comment]
Also the test code above should be
import ctranslate2
print("CTranslate2 device count: ", ctranslate2.get_cuda_device_count())
print("CTranslate2 compute type CUDA 1: ", ctranslate2.get_supported_compute_types("cuda", 0))
not 
print("CTranslate2 compute type CUDA 1: ", ctranslate2.get_supported_compute_types("cuda", 1))

**Comment by paoloprandini** [comment]
Also
export CUDA_HOME="/usr/local/cuda-13.0"
export PATH="$CUDA_HOME/bin:$PATH"
is not needed because on latest DGX Spark
lrwxrwxrwx  1 root   root     22 lug  2 16:10 cuda -> /etc/alternatives/cuda
lrwxrwxrwx  1 root   root     25 lug  2 16:10 cuda-13 -> /etc/alternatives/cuda-13
drwxr-xr-x 12 root   root   4096 nov  6 18:50 cuda-13.0
and in the PATH there is 
PATH=/usr/local/cuda/bin:/opt/bin/ and so on

**Comment by paoloprandini** [comment]
And
which ptxas
gives
/usr/local/cuda/bin/ptxas
so
export TRITON_PTXAS_PATH="$CUDA_HOME/bin/ptxas"
is not needed

**Comment by paoloprandini** [comment]
export TORCH_CUDA_ARCH_LIST="8.0 9.0 10.0 12.0 12.1a"
has no effect on the above 
ptxas fatal : Value 'sm_121a' is not defined for option 'gpu-name'

**Comment by paoloprandini** [comment]
I run
cp /usr/local/cuda/bin/ptxas /home/paolo/wlk/lib/python3.12/site-packages/triton/backends/nvidia/bin/

**Comment by paoloprandini** [comment]
Now it works!
